services:
  auth:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./:/app
      - data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; s=socket.socket(); s.connect(('127.0.0.1',5000)); print('ok')"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s

volumes:
  data:
